version: '3.9'

services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=${POSTGRESQL_ADDON_PASSWORD}
      - POSTGRES_USER=${POSTGRESQL_ADDON_USER}
      - POSTGRES_DB=${POSTGRESQL_ADDON_DB}
    volumes:
      - ./web/init.sql:/docker-entrypoint-initdb.d/init.sql
